apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev-research-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: research-app
      component: frontend
  template:
    metadata:
      labels:
        app: research-app
        component: frontend
        tier: web
        environment: dev
    spec:
      containers:
        - name: frontend
          image: lukky175/research-summarizer-frontend:latest
          ports:
            - containerPort: 80
