apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret/secret.yaml
  - mongo/mongo-deployment.yaml
  - mongo/mongo-pvc.yaml
  - mongo/mongo-service.yaml
  - backend/backend-deployment.yaml
  - backend/backend-service.yaml
  - backend/hpa-backend.yaml
  - frontend/frontend-deployment.yaml
  - frontend/frontend-service.yaml
  - frontend/hpa-frontend.yaml
  - ingress/ingress.yaml
