apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev-research-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: research-app
      component: backend
  template:
    metadata:
      labels:
        app: research-app
        component: backend
        tier: api
        environment: dev
    spec:
      containers:
        - name: backend
          image: lukky175/research-summarizer-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/loginApp
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GEMINI_API_KEY
