apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: research-app-ingress
  namespace: dev-research-app
spec:
  ingressClassName: traefik
  rules:
    - host: lukkyy.online
      http:
        paths:
          # Backend API routes
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          - path: /register
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          - path: /validate
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          - path: /summarize
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          # Every Other Request â†’ frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
